/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as megalinkSol from "./Megalink.sol";
export { DailyAttendance__factory } from "./DailyAttendance__factory";
export { Forwarder__factory } from "./Forwarder__factory";
export { Vault__factory } from "./Vault__factory";
