/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aceSol from "./ACE.sol";
export type { aceSol };
import type * as megalinkSol from "./Megalink.sol";
export type { megalinkSol };
export type { DailyAttendance } from "./DailyAttendance";
export type { Forwarder } from "./Forwarder";
export type { Tether } from "./Tether";
export type { Vault } from "./Vault";
